### ISSUE TITLE
List#sort does not cause {{#each key}} to update

### ISSUE THREAD

**Issue by asavoy** [bitovi/canjs#1566]
When using the can/list/sort plugin in CanJS 2.2.1.

See http://jsbin.com/cogafezomo/2/edit?html,js,output

It will update a list rendered with `{{#key}}` but not when rendered with `{{#each key}}`.

**Comment by akagomez** [comment]
The reason this isn't working is because of additional text nodes in the template (whitespace, new lines, etc).

This will work with those removed.. http://jsbin.com/fomequfosa/1/edit?html,js,output

That said, this issue exposes others at the DOM manipulation layer of the Sort plugin. 

@daffl and I will be taking a look later today.
