### ISSUE TITLE
can.List.replace equivalent in can.Map

### ISSUE THREAD

**Issue by wishabhilash** [bitovi/canjs#1609]
Is there any way to achieve what replace() achieves for can.List, in can.Map???

I have tried using can.Map.setup() to insert an object but it won't trigger any change in mustache. The bindings don't work for such an activity.

Am basically loading around 200 objects into can.Map and it takes a long time. Is there a way to shorten it???

Object hierarchy:
    {
        "p": {"a": "a", "v": "v"},
        "q": {"a": "a", "v": "v"},
        "r": {"a": "a", "v": "v"}
        "r": {"a": "a", "v": "v"}
        "t": {"a": "a", "v": "v"}
         .
         .
         .
    }

**Comment by justinbmeyer** [comment]
I'm not sure I understand the question.  

```js
map.attr( NEWVALUES, true)
```

does what replace does.  the `true` does a hard set.

However, there are still going to be 200 properties changing.  

You could use LazyMap and LazyList which might perform better.

If you are having performance problems, make sure that there are no "change" event handlers in your application.  "change" sets up bubbling, which adds a heavy cost.  You can avoid "change" event handlers by either listening to the specific values you want to change, or by wrapping the value you want to produce in a `can.compute`.

I'm closing this issue, because there is a way to do what `.replace()` does.  If you have questions about performance, please create a stackoverflow question and link to it from here.

Thanks!

**Comment by wishabhilash** [comment]
Thanks man... I will try using LazyMap and check for performance change. If required will definitely heed for stackoverflow and put a link here.
