### ISSUE TITLE
stache helpers are not evaluated when component is included in a parent mustache template

### ISSUE THREAD

**Issue by shcarrico** [bitovi/canjs#1614]
http://jsfiddle.net/shcarrico/vvm600wa/

change l5 to `can.mustache` and the helper will evaluate as expected.

**Comment by justinbmeyer** [comment]
We aren't supporting using can.stache and can.mustache together.  The reason is that their use of nodeLists are incompatible.  Making them work together would undermine a lot of the performance improvements in stache.  Stache doesn't have to look through a global nodeList map to build its hierarchy while Mustache does.  The only way for them to work together would be to have Stache also looking through this global nodeList map.
