### ISSUE TITLE
Compute code gets inserted into DOM with Stache sometimes

### ISSUE THREAD

**Issue by dylanrtt** [bitovi/canjs#1617]
When you render a Stache template with a binding to a key that is not a can.compute, if it changes to a can.compute, the compute's code will be inserted into the DOM. This does not happen in Mustache.

Here's a fiddle.

http://jsfiddle.net/qYdwR/2471/

**Comment by moschel** [comment]
@dylanrtt added a fix ^

**Comment by justinbmeyer** [comment]
@brianmoschel I dont think this is the right fix.

**Comment by justinbmeyer** [comment]
So, looking into this issue, I think it's worth some discussion.

I'm not sure comptues should be allowed as values of a can.Map.  The primary reason is that it will undermine a some of the performance gains in stache because we won't be able to use "single bind" computes.

"single bind" computes are a strategy that if a single map property is being observed, we only listen to just that property change and never look for other observables to listen to.

This speeds up live binding quite a bit.  Having a compute as a potential property means we might always need to check for that compute and listen to it.  

Btw, this works if you don't initially have an empty property value.

**Comment by WheteThunger** [comment]
I would probably be fine with disallowing computes on maps. Computes have been manually applied to models a lot in the app I work on (some were done before the define plugin), and they recently started showing up as minor problems during the upgrade to stache, and then as very serious problems in the upgrade to can 2.2.1; it took several full days to understand and fix the problems with computes being manually applied to maps.

In almost all cases where computes went wrong in my app, I would say the usage was inappropriate. I was usually able to work around the issue by just rethinking the problem and coming to a more appropriate solution. For example, in one case, a "display" compute was being set on every model in a list, and the compute was depending on the other values in the list. Since it was really performing view logic, and thus did not belong in define, I simply changed it to a local stache helper and fixed the problem.

The only usage I can think of where we needed to apply computes in an unorthodox way had to due with a model list because we can't currently use define on lists. Maybe we could get #1127 expedited sooner...

**Comment by dylanrtt** [comment]
I would probably be fine with disallowing computes on maps. Computes have been manually applied to models a lot in the app I work on (some were done before the define plugin), and they recently started showing up as minor problems during the upgrade to stache, and then as very serious problems in the upgrade to can 2.2.1; it took several full days to understand and fix the problems with computes being manually applied to maps.

In almost all cases where computes went wrong in my app, I would say the usage was inappropriate. I was usually able to work around the issue by just rethinking the problem and coming to a more appropriate solution. For example, in one case, a "display" compute was being set on every model in a list, and the compute was depending on the other values in the list. Since it was really performing view logic, and thus did not belong in define, I simply changed it to a local stache helper and fixed the problem.

The only usage I can think of where we needed to apply computes in an unorthodox way had to due with a model list because we can't currently use define on lists. Maybe we could get #1127 expedited sooner...

**Comment by justinbmeyer** [comment]
If I were to remove the "single bind" exception, it drops the spinning circle speed from about 16ms per loop to about 12ms per loop.

I suppose I could only setup "single bind" exception on values that were not `undefined`, or `computes`.

So, if you switched from `undefined` to compute, live-binding would be slow, but would work.  If you switch from `undefined` to `"foo"`, live binding will be slow, but work.

If you switched from `null` to a compute, live binding will not work.

If you switch from `null` to `"foo"` live binding will be fast and work.

Alternatively, there might be a way to detect a return of observable values and switch off the exception.  This would be ideal, but hard to wire up.

**Comment by dylanrtt** [comment]
Either option sounds fine, but at this point I don't really see this as much of an issue anymore. I was able to work around it fairly easily and I just figured you guys should be aware of it since it seemed like a regression. Up to you how you want to deal with it, whether that be a fix or just documentation.

**Comment by justinbmeyer** [comment]
@dylanrtt I was able to "have our cake and eat it" with an improved compute that is able to switch between the "single bind" and the "multi bind".  This way we can have good performance, but if suddenly a compute is added, `can.stache` and actually `can.mustache` will handle it.
