### ISSUE TITLE
Use Function.prototype.bind if available

### ISSUE THREAD

**Issue by daffl** [bitovi/canjs#1632]
Currently it always returns a wrapper function (see https://github.com/bitovi/canjs/blob/master/util/jquery/jquery.js#L98)

**Comment by rjgotten** [comment]
> @daffl:
> Currently it always returns a wrapper function

Technically, `Function.prototype.bind` also returns a wrapping function...

```js
function foo() {};
console.log(foo == foo.bind(this)); // false
```

The risk in using `Function.prototype.bind` 'if available', is that it may have been polyfilled. (E.g. Modernizr contains a polyfill for it, built into the library.)

The reason CanJS has its own `proxy` method instead of straight-up re-using jQuery is the fact that the argument checking and currying that is part of jQuery's `proxy` method was deemed too detrimental to performance, because CanJs heavily leans on `proxy` internally and calls it many times.

A fully compliant polyfill for `Function.prototype.bind` would be just as stringent in its checks (if not even moreso) than jQuery's `proxy` method and would undoubtedly lead to comparable performance characteristics and thus the same performance problems...

**Comment by daffl** [comment]
Good point. I didn't remember the reason for our own proxy. We should probably leave it then although it would be interesting to see if there is a performance difference between `Function.prototype.bind` and your own wrapper.

**Comment by justinbmeyer** [comment]
I think we should make this change.  If some project is accidentally picking up Modernizr's `.bind`, that project can pretty easily patch can.proxy.

Yes, jQuery's .proxy was slow, but not the bottleneck in performance.

The BIG reason for this is debugging.  If you look at almost any function in CanJS, you get back a can.proxy generated function.  Instead if Function.prototype.bind is used, you will see your original source function.

IMO, the trade offs are worth it.

**Comment by rjgotten** [comment]
> Instead if Function.prototype.bind is used, you will see your original source function.

Fyi: maybe that's the case with Chrome and its development tools, but in Firefox with Firebug you get back a different function with its source display set to `[native code]` and no link to the location where the original function is defined.

If debugging is the big reason that makes it worth the trade-off, perhaps you want to consider this fact as well.

**Comment by justinbmeyer** [comment]
@rjgotten I was aware of the issue with Firebug, but I still think it's worth it.  In my trainings, I think over 90% of people use chrome now.  

Perhaps for other devs, we can put an __proxied property on the returned function that points to the original function.
