### ISSUE TITLE
Conditional can-EVENT bindings don't work in stache

### ISSUE THREAD

**Issue by akagomez** [bitovi/canjs#1650]
Demo: http://jsfiddle.net/akagomez/gtt4vf04/

Problem: 
Adding a conditional `{{#if whatever}}` around a `can-click="{methodName}"` breaks the binding even if the conditional is `true`.

Test: https://github.com/bitovi/canjs/commit/d218badee8571b42d7c2b6ed37202e3553ee6903

/cc @justinbmeyer @daffl

**Comment by moschel** [comment]
I feel like I've filed this and worked on it before. I don't remember what happened to it. I'll investigate.

**Comment by moschel** [comment]
The PR I was thinking of was https://github.com/bitovi/canjs/pull/1347

**Comment by akagomez** [comment]
Darn. I probably could had reused that test and just changed `mustache` to `stache`.

**Comment by kylegifford** [comment]
@daffl @justinbmeyer I'm a bit stuck on this, could use your input. The contents of the {{#if}} are returned on https://github.com/bitovi/canjs/blob/master/view/stache/mustache_core.js#L114, but for this case, it is something like `"can-click="foo" "`. I believe what needs to happen is instead of just returning this as a string, it should compile and hydrate the contents of the result. Something like:

```
var result = rendererWithScope(newScope, newOptions || parentOptions, parentNodeList || nodeList);
if(result) {
    // result.compile().hydrate()
}
```

Does this seem like the right place to put this code? If so, what method can be used to compile and/or hydrate the result? Also, is there anything that needs to be done to remove the binding once `"can-click="foo" "` is removed from the DOM? Thanks!

**Comment by whitecolor** [comment]
this still doesn't work in lates minor and this too https://github.com/bitovi/canjs/issues/1800

**Comment by akagomez** [comment]
@whitecolor The PR hasn't been merged yet.

**Comment by whitecolor** [comment]
@akagomez ok, hope to see this soon

**Comment by whitecolor** [comment]
@daffl will this work on minor?

**Comment by daffl** [comment]
I just tried a merge and it turned out to be a huge pain so probably not until two weeks from now.

**Comment by whitecolor** [comment]
@daffl have a look at this https://github.com/bitovi/canjs/issues/1800 too please, perchance related.

**Comment by justinbmeyer** [comment]
@daffl Did the merge: #1806

**Comment by daffl** [comment]
I was  indeed being complicated. Thanks!
