### ISSUE TITLE
Create ~ helper for joining to the baseURL

### ISSUE THREAD

**Issue by matthewp** [bitovi/canjs#1816]
This will be used to join to the root, for example images:

```handlebars
<img src="{~ 'images' status 'indicator.png'}" />
```

will convert to:

```handlebars
<img src="https://somecdn.com/images/complete/indicator.png" />
```

If the module loader's baseUrl is `https://somecdn.com/`

### ~ path...

This will typecheck for StealJS/SystemJS, RequireJS, to get the module loader baseUrl, and fallback to document.baseURI to use as the base url that the arguments are joined to.

If the path is relative it will use the module's path, if available. https://github.com/bitovi/canjs/issues/1817 is needed for that functionality.

**Comment by rjgotten** [comment]
> This will typecheck for StealJS/SystemJS, RequireJS, to get the module loader baseUrl,

The base URL of the module loader is not necessarily the base URL of a website.
Its common to root JS module loader at a subpath holding scripts: `http://www.example.com/scripts/`, especially when using far future expires headers coupled with a cache-busting version in the path: `http://www.example.com/scripts/1.0.0/`

The domain/authority part is not necessarily the base URL of a website either as you can host individual applications inside subdirectories.

Application-relative URLs (the term used by Microsoft, which has been using a leading tilde for these type of URLs since the first version of ASP.NET) are best handled in user code, by having users describe how the base application url should be mapped.

E.g. using RequireJS, the following does the job:

```html
<head>
  <script>
  // First create a module mapping for the '~' symbol to
  // a domain-relative, protocol-relative or absolute root
  // url. (Don't make it path relative! That won't work!)
  require.config({
    map : { "*" : {
      "~" : "/application/."
    }}
  })
  </script>
</head>
```

```js
define([ "require" ], function( require ) {
  // Then use the `require.toUrl()` method.
  // In this case, it will produce "/application/content/images/example.jpg"
  var fullUri = require.toUrl( "~/content/images/example.jpg" );
});
```

**Comment by matthewp** [comment]
Great point. We can allow the user to set a variable, probably `can.baseUrl` which will be used as the first check to get the application base url for cases where the module loader baseUrl is not the same.

**Comment by matthewp** [comment]
This is in minor.
