### ISSUE TITLE
Handlebars use in canjs

### ISSUE THREAD

**Issue by shivendravikram** [bitovi/canjs#1858]
Any limitation using handlebars by stache.....I tried to find the handlebarjs file in your canjs build but no luck...:(

**Comment by daffl** [comment]
The Stache engine is syntax compatible with Handlebars which means that you can use most Handlebars templates without any modifications. There are some small differences in helpers because stache helpers are live-bindable (whereas Handlebars doesn't have live-updating templates at all).

We don't have a specific list of the differences at the moment but you can find all the documentation at http://canjs.com/docs/can.stache.html and we can always help out migrating if you run into any issues.
