### ISSUE TITLE
can.batch.start/stop causes can.List with length>1 to render last element twice

### ISSUE THREAD

**Issue by stevenvachon** [bitovi/canjs#680]
```handlebars
{{#each arr}} {{.}} {{/each}}
```
```js
for (var i=1; i<=2; i++) {
    this.arr.push(i);
}
```
will produce `1,2`, however:
```js
can.batch.start();
for (var i=1; i<=2; i++) {
    this.arr.push(i);
}
can.batch.stop();
```
will produce `1,2,2`.

?

http://jsfiddle.net/prometh/34YZP/

**Comment by justinbmeyer** [comment]
@stevenvachon great catch.  @cklanac , this is maybe because `two` add events are fired and `#each`'s add and remove handlers (https://github.com/bitovi/canjs/blob/master/view/live/live.js#L159) are not checking the batchNum.

You can see how https://github.com/bitovi/canjs/blob/master/compute/compute.js#L233 checks the batch num.

 ... however on second thought, that doesn't seem like the likely problem. Maybe the arguments are not right for the add event.

**Comment by cklanac** [comment]
@stevenvachon Thanks for submitting the issues. This issue is caused by the `{{#if breaks.length}}` helper interacting with the batched update and `{{#each breaks}}` helper. We've a fix to the next release. 

In the meantime, you can workaround the issue by removing the `.length` from the if helper -  simply `{{#if breaks}}... {{/if}}`, or change `{{#each breaks}}` helper to simply `{{#breaks}}{{.}}{{/breaks}}`. 

http://canjs.com/docs/can.stache.Sections.html#section_Iteration

http://jsfiddle.net/cklanac/wfm6k20r/
